### ISSUE TITLE
Geo-code is featured in one of our blogs

### ISSUE THREAD

**Issue by binbalenci** [jifalops/geo-codec#2]
Hi jifalops,

I am Binh, the author of the series [Web Components Wednesday](https://vaadin.com/blog?tag=wcw), where I will review some components every Wednesday. 

Your component was featured in the blog [Introducing geo-location, a web component which lets you easily locate, track or reverse geocode your current location](https://vaadin.com/blog/introducing-geo-location-a-web-component-which-lets-you-easily-locate-track-or-reverse-geocode-your-current-location). I found geo-codec to be extremely useful and easy to use.

So have a read and it would be great if you, the original author can have a word in the comment section.

Cheers,
Binh

**Comment by jifalops** [comment]
Thanks for the write-up!

**Comment by binbalenci** [comment]
Warmly welcome, jifalops! 

Do you mind if I add the Directory badges for the rest of your components collection? I have reviewed them all and they possess really good qualities.

Many vendors and individuals (Collaborne, LostInBrittany, RoXus, FabricElements) have put our badges  in their repositories and I believe people should be more aware of your listing, as well.

**Comment by jifalops** [comment]
Sure I don't see why not. I'm a fan of Vaadin :)

**Comment by binbalenci** [comment]
Awesome! May I ask the Vaadin framework or which part of Vaadin?
